const GET_BOARDS = 'GET_BOARDS';
const ADD_BOARD = 'ADD_BOARD';
const ADD_CARD = 'ADD_CARD';
const ADD_LIST = 'ADD_LIST';
const DELETE_LIST = 'DELETE_LIST';

export { GET_BOARDS, ADD_BOARD, ADD_CARD, ADD_LIST, DELETE_LIST };
